#!/usr/bin/env sh

if [ $# -eq 0 -a $# -gt 2 ]
  then
  echo "To setup the aliases write:\t\t\tsudo./aliases up/down #aliases\n"
  exit 1
fi
re='^[0-9]+$'
if ! [[ $2 =~ $re ]]
  then
   printf "To setup the aliases write:\t\t\tsudo ./aliases up/down #aliases\n"
   exit 1
fi

if [ $1 = "up" ]
  then
    for ((i=0; i<=$2; i++))
      do
      ifconfig lo0 alias 128.0.0.$i $1
      echo "ifconfig lo0 alias 128.0.0.$i $1"
    done

fi

if [ $1 = "down" ]
  then
    for ((i=0; i<=$2; i++))
      do
      ifconfig lo0 $1 128.0.0.$i
      echo "ifconfig lo0 delete 128.0.0.$i"
    done

fi
